# This is a basic workflow to help you get started with Actions

name: Create async api docu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "rest-0.3.1" ]
    paths:
      - 'docs/Kafka-Events-Specification/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Set up Node.js (if using Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version you need
      
      - name: Run a setup asyncapi generator cli
        run: npm install -g @asyncapi/cli

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ls -la
        run: | 
          ls -la
          cd Kafka-Events-Specification
          ls -la

      # Runs a single command using the runners shell
      - name: Generate async api docu
        run: asyncapi generate fromTemplate ./Kafka-Events-Specification/asyncAPI-v0.3.0.yaml @asyncapi/html-template -o docs/Kafka-Events-Specification

      # Commit all changed files back to the repository
      - name: Commit generated asyncapi html output
        uses: stefanzweifel/git-auto-commit-action@v5
